name: Self Healing Server

on:
  schedule:
    - cron: "*/1 * * * *"

  workflow_dispatch:

jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: SSH into EC2

      uses: appleboy/ssh-action@v1

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}

        script: |

          cd ~/self-healing

          ./monitor.sh
